# Form implementation generated from reading ui file 'desktop_weather.ui'
#
# Created by: PyQt6 UI code generator 6.1.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 553)
        Dialog.setStyleSheet("background-color: rgb(0, 191, 255);\n"
"")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 250))
        self.frame.setStyleSheet("background-color: #f9a6aa\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, -30, 341, 181))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.line_city = QtWidgets.QLineEdit(self.frame)
        self.line_city.setGeometry(QtCore.QRect(30, 100, 321, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.line_city.setFont(font)
        self.line_city.setStyleSheet("background-color:blue;\n"
"border: 6px;\n"
"border-radius: 20;\n"
"border-color: red;\n"
"")
        self.line_city.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_city.setObjectName("line_city")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(100, 470, 201, 71))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"font: 25 12pt \"Perpetua Titling MT\";\n"
"background-color: red;\n"
"border-radius: 20;\n"
"}\n"
"QPushButton::pressed{\n"
"background-color: rgb(255, 170, 0);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.line_city_2 = QtWidgets.QLineEdit(Dialog)
        self.line_city_2.setGeometry(QtCore.QRect(40, 260, 321, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.line_city_2.setFont(font)
        self.line_city_2.setStyleSheet("background-color:blue;\n"
"border: 6px;\n"
"border-radius: 20;\n"
"border-color: red;\n"
"")
        self.line_city_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_city_2.setObjectName("line_city_2")
        self.line_city_3 = QtWidgets.QLineEdit(Dialog)
        self.line_city_3.setGeometry(QtCore.QRect(40, 330, 321, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.line_city_3.setFont(font)
        self.line_city_3.setStyleSheet("background-color:blue;\n"
"border: 6px;\n"
"border-radius: 20;\n"
"border-color: red;\n"
"")
        self.line_city_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_city_3.setObjectName("line_city_3")
        self.line_city_4 = QtWidgets.QLineEdit(Dialog)
        self.line_city_4.setGeometry(QtCore.QRect(40, 400, 321, 51))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.line_city_4.setFont(font)
        self.line_city_4.setStyleSheet("background-color:blue;\n"
"border: 6px;\n"
"border-radius: 20;\n"
"border-color: red;\n"
"")
        self.line_city_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_city_4.setObjectName("line_city_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Weather in city"))
        self.line_city.setText(_translate("Dialog", "1313"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.line_city_2.setText(_translate("Dialog", "1313"))
        self.line_city_3.setText(_translate("Dialog", "1313"))
        self.line_city_4.setText(_translate("Dialog", "1313"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
